<?php 

define('AGK_PAGE_SHOW', 25);

define('AGK_ERROR_MESSAGE_SESSION_EXPIRED', "You are not allowed to access without Login");

define('AGK_GENERAL_BUTTON_APPLY', "Terapkan");
define('AGK_GENERAL_BUTTON_CLASS', "btn btn-primary");
define('AGK_GENERAL_BUTTON_CLASS_2', "btn btn-secondary btn-sm");
define('AGK_GENERAL_BUTTON_CLASS_3', "btn btn-warning btn-sm");
define('AGK_GENERAL_BUTTON_CLASS_SMALL', "btn btn-warning btn-sm");
define('AGK_GENERAL_BUTTON_CLASS_REMOVED', "btn btn-danger btn-sm");
define('AGK_GENERAL_BUTTON_CLASS_RESET', "btn btn-warning btn-sm");
define('AGK_GENERAL_BUTTON_CLASS_SAVE', "btn btn-primary btn-sm");
define('AGK_GENERAL_BUTTON_ACTION', '<i class="fas fa-ellipsis-v"></i> ');
define('AGK_GENERAL_BUTTON_ADD_NEW', '<i class="fas fa-plus"></i> Tambah Baru');
define('AGK_GENERAL_BUTTON_BACK', '<i class="fas fa-chevron-left"></i> Kembali');
define('AGK_GENERAL_BUTTON_CLOSED', '<i class="fas fa-times"></i> Tutup');
define('AGK_GENERAL_BUTTON_DELETE', '<i class="fas fa-times"></i> Hapus');
define('AGK_GENERAL_BUTTON_DELETE_PERMANENTLY', '<i class="fas fa-times text-danger"></i> Hapus Permanen');
define('AGK_GENERAL_BUTTON_DETAIL', '<span class="no-icon"></span> Detil');
define('AGK_GENERAL_BUTTON_EDIT', '<i class="fas fa-pencil-alt"></i> Ubah');
define('AGK_GENERAL_BUTTON_EXPORT', '<i class="fas fa-download"></i> Unduh');
define('AGK_GENERAL_BUTTON_EXPORT_EXCEL', '<i class="fas fa-file-excel text-success"></i> Unduh ke Excel');
define('AGK_GENERAL_BUTTON_EXPORT_PDF', '<i class="fas fa-file-pdf text-danger"></i> Unduh ke PDF');
define('AGK_GENERAL_BUTTON_EXPORT_PRINT', '<i class="fas fa-print"></i> Cetak');
define('AGK_GENERAL_BUTTON_FILTER', '<i class="fas fa-search"></i> Pencarian');
define('AGK_GENERAL_BUTTON_HELP', '<i class="fas fa-exclamation-circle"></i> Bantuan');
define('AGK_GENERAL_BUTTON_PROPERTY', '<i class="fas fa-folder text-warning"></i> Properti');
define('AGK_GENERAL_BUTTON_REFRESH', '<i class="fas fa-undo fa-flip-horizontal"></i> Muat Ulang');
define('AGK_GENERAL_BUTTON_RESTORE', '<i class="fas fa-redo text-warning"></i> Pindahkan ke Folder Utama');
define('AGK_GENERAL_BUTTON_RESET', '<i class="fas fa-sync"></i> Ulangi');
define('AGK_GENERAL_BUTTON_SAVE', '<i class="fas fa-check"></i> Simpan');
define('AGK_GENERAL_BUTTON_SEARCH', '<i class="fas fa-search"></i> Cari');
define('AGK_GENERAL_BUTTON_TRASH', '<i class="fas fa-trash"></i> Sampah');
define('AGK_GENERAL_BUTTON_TRASH_ROW', '<i class="fas fa-trash text-danger"></i> Pindahkan ke Folder Sampah');
define('AGK_GENERAL_BUTTON_UPDATE', '<i class="fas fa-check"></i> Simpan Perubahan');

define('AGK_GENERAL_FORM_INPUT_CLASS', "form-control form-control-sm");
define('AGK_GENERAL_FORM_GROUP_CLASS', "input-group input-group-sm");
define('AGK_GENERAL_TABLE_ICON_DROPDOWN', '&nbsp;<i class="fas fa-ellipsis-v"></i>&nbsp; ');

define('AGK_TH_ACTION_ICON', '<i class="fas fa-long-arrow-alt-left"></i>  T <i class="fas fa-long-arrow-alt-right"></i>');
define('AGK_TH_BESARAN_PERSENTASE_DENDA', 'Denda (%)');
define('AGK_TH_CATEGORY', 'Kategori');
define('AGK_TH_CODE', 'Kode');
define('AGK_TH_CONTACT', 'Kontak');
define('AGK_TH_DATE', 'Tanggal');
define('AGK_TH_JANGKA_WAKTU_PENERBITAN', 'Jangka Waktu Penerbitan');
define('AGK_TH_KETERANGAN_PERINGKAT', 'Keterangan Peringkat');
define('AGK_TH_NAME', 'Nama');
define('AGK_TH_NAME_EMITEN', 'Nama Emiten');
define('AGK_TH_NOMINAL_PEMBAYARAN_KUPON', 'Nominal Pembayaran Kupon');
define('AGK_TH_NOMINAL_PENERBITAN', 'Nominal Penerbitan');
define('AGK_TH_PERCENTASE_PEMBAYARAN_KUPON', 'Pembayaran Kupon (%)');
define('AGK_TH_PERIODE_PEMBAYARAN_KUPON', 'Periode Pembayaran Kupon');

// Disctionary start
define('AGK_LANG_ID_WORD_ADD_NEW_CARD', 'Tambah Kartu Baru');
define('AGK_LANG_ID_WORD_ADDRESS', 'Alamat');
define('AGK_LANG_ID_WORD_ADDITIONAL_INFORMATION', 'Informasi Tambahan');
define('AGK_LANG_ID_WORD_ADDITIONAL_INFORMATION_description', 'Bagian ini berisi informasi tambahan lainnya perusahaan jika ada.');
define('AGK_LANG_ID_WORD_ARTICLES_OF_ASSOCIATION', 'Anggaran Dasar');
define('AGK_LANG_ID_WORD_BY_BEING_SELECTED', 'Dengan Dipilih');
define('AGK_LANG_ID_WORD_CAN_CHOOSE_MORE_THAN_ONE', 'Dapat dipilih lebih dari satu');
define('AGK_LANG_ID_WORD_CATEGORY', 'Kategori');
define('AGK_LANG_ID_WORD_CITY', 'Kota');
define('AGK_LANG_ID_WORD_CITY_description', 'Pilih Provinsi terlebih dahulu untuk menampilkan pilihan Kota.');
define('AGK_LANG_ID_WORD_CODE', 'Kode');
define('AGK_LANG_ID_WORD_COUNTRY', 'Negara');
define('AGK_LANG_ID_WORD_CREATED_AT', 'Dibuat Pada');
define('AGK_LANG_ID_WORD_DELETE', 'Hapus Permanen');
define('AGK_LANG_ID_WORD_DISTRICTS', 'Kecamatan');
define('AGK_LANG_ID_WORD_DISTRICTS_description', 'Pilih Kota terlebih dahulu untuk menampilkan pilihan Kecamatan.');
define('AGK_LANG_ID_WORD_DOCUMENT_LEGALITY', 'Dokumen Legalitas');
define('AGK_LANG_ID_WORD_DOCUMENT_LEGALITY_description', 'Bagian ini berisi rincian identitas data legalitas perusahaan.');
define('AGK_LANG_ID_WORD_EDIT_CARD', 'Ubah Data Kartu');
define('AGK_LANG_ID_WORD_EMAIL', 'Email');
define('AGK_LANG_ID_WORD_ENTRIES', 'entri');
define('AGK_LANG_ID_WORD_FAX_NUMBER', 'No. Fax');
define('AGK_LANG_ID_WORD_FROM', 'Dari');
define('AGK_LANG_ID_WORD_GENERAL', 'Umum');
define('AGK_LANG_ID_WORD_GENERAL_INFORMATION', 'Informasi Umum');
define('AGK_LANG_ID_WORD_GENERAL_INFORMATION_description', 'Bagian ini berisi informasi umum tentang perusahaan seperti kategori, nama, alamat dan kontak');
define('AGK_LANG_ID_WORD_LEGALITY', 'Legalitas');
define('AGK_LANG_ID_WORD_LIST_ALL_CARD', 'Daftar Semua Kartu');
define('AGK_LANG_ID_WORD_MANAGEMENT_REGISTER_ID_CARD', 'Registrasi Identitas Kartu Manajemen');
define('AGK_LANG_ID_WORD_MANAGEMENT_REGISTER_ID_CARD_description', 'Nomor KTP seluruh pengurus.');
define('AGK_LANG_ID_WORD_MANAGEMENT_STRUCTURE_LIST', 'Daftar Susunan Manajemen');
define('AGK_LANG_ID_WORD_MANAGEMENT_STRUCTURE_LIST_description', 'Daftar struktur organisasi kepengurusan.');
define('AGK_LANG_ID_WORD_MANAGEMENT_TAX_NUMBER_CARD', 'NPWP Manajemen');
define('AGK_LANG_ID_WORD_MANAGEMENT_TAX_NUMBER_CARD_description', 'Daftar Nomor Kartu NPWP Manajemen');
define('AGK_LANG_ID_WORD_MEMORANDUM_OF_ASSOCIATION', 'Akta Pendirian');
define('AGK_LANG_ID_WORD_MODIFIED_AT', 'Diubah Pada');
define('AGK_LANG_ID_WORD_MOVE_TO_BIN', 'Sampah');
define('AGK_LANG_ID_WORD_NAME', 'Nama');
define('AGK_LANG_ID_WORD_NIB', 'NIB');
define('AGK_LANG_ID_WORD_NPWP', 'NPWP');
define('AGK_LANG_ID_WORD_OF', 'Dari');
define('AGK_LANG_ID_WORD_OTHER_DOCUMENT_REQUIREMENT', 'Dokumen Lainnya yang Dibutuhkan');
define('AGK_LANG_ID_WORD_OTHER_DOCUMENT_REQUIREMENT_description', 'Dokumen pendukung lainnya.');
define('AGK_LANG_ID_WORD_PHONE_NUMBER', 'No. Telp.');
define('AGK_LANG_ID_WORD_PIC_INFORMATION', 'Informasi Penanggung Jawab');
define('AGK_LANG_ID_WORD_PIC_INFORMATION_description', 'Bagian ini berisi informasi penanggung jawab perusahaan seperti nama, email dan kontak.');
define('AGK_LANG_ID_WORD_POSTAL_CODE', 'Kode Pos');
define('AGK_LANG_ID_WORD_PUBLISHED', 'Publikasikan');
define('AGK_LANG_ID_WORD_PROPERTY', 'Properti');
define('AGK_LANG_ID_WORD_PROVINCE', 'Provinsi');
define('AGK_LANG_ID_WORD_REMARK', 'Catatan');
define('AGK_LANG_ID_WORD_RESTORE', 'Restore');
define('AGK_LANG_ID_WORD_SEARCH', 'Pencarian');
define('AGK_LANG_ID_WORD_SELECT', 'Pilih...');
define('AGK_LANG_ID_WORD_SEND_MAIL_TO', 'Kirim Email ke');
define('AGK_LANG_ID_WORD_SHOW', 'Tampilkan');
define('AGK_LANG_ID_WORD_SHOWING', 'Menampilkan');
define('AGK_LANG_ID_WORD_SIUP', 'SIUP');
define('AGK_LANG_ID_WORD_SKDP', 'SKDP');
define('AGK_LANG_ID_WORD_SK_KEMENKUMHAM', 'SK Kemenkumham');
define('AGK_LANG_ID_WORD_TDP', 'TDP');
define('AGK_LANG_ID_WORD_TITLE', 'Judul');
define('AGK_LANG_ID_WORD_TO', 'Ke');
define('AGK_LANG_ID_WORD_TRASH', 'Sampah');
define('AGK_LANG_ID_WORD_TYPE_AND_ENTER', 'Ketik lalu Enter');
define('AGK_LANG_ID_WORD_UPDATED', 'Diperbaharui');
define('AGK_LANG_ID_WORD_WARD', 'Kelurahan');
define('AGK_LANG_ID_WORD_WARD_description', 'Pilih Kecamatan terlebih dahulu untuk menampilkan pilihan Kelurahan/Desa');
define('AGK_LANG_ID_WORD_WEBSITE', 'Website');
// Disctionary end